// <auto-generated />
namespace Data.Context.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Characterize : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Characterize));
        
        string IMigrationMetadata.Id
        {
            get { return "202007131752073_Characterize"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
